### ISSUE TITLE
Nipap-cli on a remote server doesn't work

### ISSUE THREAD

**Issue by yauckburally** [SpriteLink/NIPAP#1125]
Hello all, 
I have install nipap-cli on an other debian server to reach and execute some requests on my nipap db.
But when i execute a commande like
`nipap address list 0/0`
It returns me this error
`Searching for prefixes in any VRF...
Traceback (most recent call last):
  File "/usr/bin/nipap", line 124, in <module>
    cmd.exe(cmd.arg, cmd.exe_options, args)
  File "/usr/lib/python3/dist-packages/nipap_cli/nipap_cli.py", line 579, in list_prefix
    vrf_q)
  File "/usr/lib/python3/dist-packages/pynipap.py", line 1103, in smart_search
    result['error'] = smart_result['error']
KeyError: 'error'`
On the server which nipap is installed,i've got no problem.
My config of .nipaprc : 
`[global]
hostname = 192.168.*.*
port     = 1337
username = ****
password = ****
default_vrf_rt = none`

I think my config is ok because when i do the same research specifying "vrf_rt" ,i have the same error but with the name of the VRF.

How to repair the error ?

**Comment by garberg** [comment]
My guess would be that this is due to different versions of NIPAP running on the backend and CLI host, there was a quite recent API change which should result in such an error.

Could you please verify that you have the same NIPAP versions installed on both hosts?
