### ISSUE TITLE
"Error 500 An internal server error occurred" when accessing WebUI

### ISSUE THREAD

**Issue by 74cmonty** [SpriteLink/NIPAP#1225]
Hi,
when I try to access the WebUI, I get this error after login:
```
Error 500 An internal server error occurred
```

This is the related error in /var/log/apache2/error.log:
```
root@ct201-nipap:~# tail /var/log/apache2/error.log
[Mon Jun 24 16:36:23.643971 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]             <pre>Traceback (most recent call last):, referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643973 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]   File "/usr/lib/python2.7/dist-packages/weberror/errormiddleware.py", line 471, in send_report, referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643976 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]     rep.report(exc_data), referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643979 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]   File "/usr/lib/python2.7/dist-packages/weberror/reporter.py", line 56, in report, referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643981 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]     self.to_addresses, msg.as_string()), referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643984 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]   File "/usr/lib/python2.7/smtplib.py", line 747, in sendmail, referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643987 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]     raise SMTPRecipientsRefused(senderrs), referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643989 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500] SMTPRecipientsRefused: {'you@yourdomain.com': (454, '4.7.1 <you@yourdomain.com>: Relay access denied')}, referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.643992 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500] </pre>, referer: http://10.97.206.201/ng/pool
[Mon Jun 24 16:36:23.645223 2019] [wsgi:error] [pid 583:tid 139810929231616] [client 10.19.90.60:53500]             </p>, referer: http://10.97.206.201/ng/pool
```

I did modify Apache's default vhost file:
```
root@ct201-nipap:~# more /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80>
        # The ServerName directive sets the request scheme, hostname and port that
        # the server uses to identify itself. This is used when creating
        # redirection URLs. In the context of virtual hosts, the ServerName
        # specifies what hostname must appear in the request's Host: header to
        # match this virtual host. For the default virtual host (this file) this
        # value is not decisive as it is used as a last resort host regardless.
        # However, you must set it for any further virtual host explicitly.
        ServerName nipap.lve.wdf.sap.corp

        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        # Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
        # error, crit, alert, emerg.
        # It is also possible to configure the loglevel for particular
        # modules, e.g.
        #LogLevel info ssl:warn

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        # For most configuration files from conf-available/, which are
        # enabled or disabled at a global level, it is possible to
        # include a line for only one particular virtual host. For example the
        # following line enables the CGI configuration for this host only
        # after it has been globally disabled with "a2disconf".
        #Include conf-available/serve-cgi-bin.conf

        WSGIScriptAlias / /etc/nipap/www/nipap-www.wsgi

        <Directory /etc/nipap/www/>
                Require all granted
        </Directory>
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```

Can you please advise to solve this issue?

THX

**Comment by steffenschumacher** [comment]
Sounds like your smtp server doesn't accept the default 'email_to' from nipap-www.ini?
Does your nipap web server run an smtp daemon? Mine doesn't and it works just fine?

**Comment by 74cmonty** [comment]
To my best knowledge there's _Postgres_ running on this server.
```root@ct201-nipap:~# ss -tulpen
Netid  State      Recv-Q Send-Q                        Local Address:Port                                       Peer Address:Port
tcp    LISTEN     0      128                                       *:22                                                    *:*                   users:(("sshd",pid=145,fd=3)) ino:30075292 sk:1 <->
tcp    LISTEN     0      128                               127.0.0.1:5432                                                  *:*                   users:(("postgres",pid=203,fd=6)) uid:108 ino:30057007 sk:2 <->
tcp    LISTEN     0      128                               127.0.0.1:1337                                                  *:*                   users:(("nipapd",pid=386,fd=8)) uid:109 ino:30070487 sk:3 <->
tcp    LISTEN     0      100                               127.0.0.1:25                                                    *:*                   users:(("master",pid=358,fd=13)) ino:30074184 sk:4 <->
tcp    LISTEN     0      128                                      :::80                                                   :::*                   users:(("apache2",pid=33201,fd=4),("apache2",pid=33200,fd=4),("apache2",pid=199,fd=4)) ino:30074133 sk:5 v6only:0 <->
tcp    LISTEN     0      128                                      :::22                                                   :::*                   users:(("sshd",pid=145,fd=4)) ino:30075294 sk:6 v6only:1 <->
tcp    LISTEN     0      128                                     ::1:5432                                                 :::*                   users:(("postgres",pid=203,fd=3)) uid:108 ino:30057006 sk:7 v6only:1 <->
tcp    LISTEN     0      100                                     ::1:25                                                   :::*                   users:(("master",pid=358,fd=14)) ino:30074185 sk:8 v6only:1 <->
```
However I didn't install it, probably this package was installed as dependency of Apache2.

**Comment by steffenschumacher** [comment]
I dont know it got on there, and that doesn’t matter much in terms of the original question?

**Comment by 74cmonty** [comment]
Well, can you please advise what the SMTP server is needed for with NIPAP?
If it's not required I can simply stop it (or delete it).

**Comment by steffenschumacher** [comment]
Im not sure, but it’d be an easy test to stop it, and see if it helps?
