### ISSUE TITLE
nipapd.service wont start - python error

### ISSUE THREAD

**Issue by mheinze9999** [SpriteLink/NIPAP#1250]
Hello,

i try to get nipapd start working but no luck. The following error occurs

root@nipap-demo:/usr/lib/python2.7/dist-packages# Traceback (most recent call last):
  File "/usr/sbin/nipapd", line 219, in <module>
    import nipap.xmlrpc
  File "/usr/lib/python2.7/dist-packages/nipap/xmlrpc.py", line 16, in <module>
    from flask.ext.compress import Compress
ImportError: No module named ext.compress

so no socket is listening.

Install on Debian 10 latest (stable) Build

Has anyone a hint?

**Comment by mheinze9999** [comment]
Hmm it seems the project is dead

**Comment by steffenschumacher** [comment]
I think you should consider using docker versions instead - that way you don't need to bother with all the install issues

**Comment by becuhkyy** [comment]
Open /usr/lib/python2.7/dist-packages/nipap/xmlrpc.py
on line 16, replace:
from flask.ext.compress import Compress
with:
from flask_compress import Compress

That is a dirty "fix", and there might be other bugs laying around.

**Comment by mheinze9999** [comment]
Ok, i'll give it a try

I wonder why it's called the best IP management tool and why it doesn't even install. No error is displayed during the installation and it does not start. No, it's much worse, it starts (according to systemd) and ends silently.
I've been working in Linux since Slackware 2.1 and there were projects that came and went, but they all worked ... 'out of the box'
It wouldn't be a problem to pay for it either, but to leave it online like that is unkind, then take it offline, it's more honest.

regards

**Comment by steffenschumacher** [comment]
If they took it online no-one would be able to fix things - I assume you mean the packages? sure, if they don't build.
If its not a problem to pay, you could pay developers to fix things?

**Comment by garberg** [comment]
This issue has been fixed, closing.
