### ISSUE TITLE
Got internal server error on web UI

### ISSUE THREAD

**Issue by titanotom** [SpriteLink/NIPAP#1350]
I got internal server error on nipap web UI after upgrade. This the log

[Wed Oct 25 17:20:30.716799 2023] [wsgi:error]  Traceback (most recent call last):
[Wed Oct 25 17:20:30.716823 2023] [wsgi:error]    File "/etc/nipap/www/nipap-www.wsgi", line 7, in <module>
[Wed Oct 25 17:20:30.716827 2023] [wsgi:error]      from nipapwww import create_app
[Wed Oct 25 17:20:30.716837 2023] [wsgi:error]  ImportError: No module named 'nipapwww'
[Wed Oct 25 17:20:30.859976 2023] [wsgi:error]  mod_wsgi (pid=30011): Target WSGI script '/etc/nipap/www/nipap-www.wsgi' cannot be loaded as Python module., referer: https://ipam.te.net.id/
[Wed Oct 25 17:20:30.860010 2023] [wsgi:error]  mod_wsgi (pid=30011): Exception occurred processing WSGI script '/etc/nipap/www/nipap-www.wsgi'., referer: https://ipam.te.net.id/
[Wed Oct 25 17:20:30.860062 2023] [wsgi:error]  Traceback (most recent call last):, referer: https://ipam.te.net.id/
[Wed Oct 25 17:20:30.860079 2023] [wsgi:error]    File "/etc/nipap/www/nipap-www.wsgi", line 7, in <module>, referer: https://ipam.te.net.id/
[Wed Oct 25 17:20:30.860082 2023] [wsgi:error]      from nipapwww import create_app, referer: https://ipam.te.net.id/
[Wed Oct 25 17:20:30.860092 2023] [wsgi:error]  ImportError: No module named 'nipapwww', referer: https://ipam.te.net.id/

is it something wrong with nipapwww?

**Comment by titanotom** [comment]
nipapd and nipap-www is the newest version (0.31.2-1) and i already install libapache2-mod-wsgi-py3.

What a notification?the only notification i got when i ran apt upgrade was the option of generate secret key (automatic or manually)

**Comment by garberg** [comment]
Okay, that's odd.. I presume you have restarted Apache? If you just start an interactive Python 3 interpreter, can you import nipapwww?

What distribution are you running NIPAP on?

**Comment by titanotom** [comment]
Yes i have restarted apache and nipapd. How to import nipapwww?

I'm running on ubuntu 16.04

**Comment by garberg** [comment]
Just run ```python3``` in a shell and then ```import nipapwww```.

Ubuntu 16.04 ships with Python 3.5, I haven't tested NIPAP with versions < 3.6. Automated tests are run on Ubuntu 20.04, I've tested manually on 18.04. Would you consider a dist upgrade?

**Comment by titanotom** [comment]
This what i got when tried to import nipapwww on version 3.5 and 3.6

Python 3.5.2 (default, Jan 26 2021, 13:30:48)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nipapwww
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'nipapwww'
>>> quit()

Python 3.8.6 (default, Dec  6 2020, 14:28:49)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nipapwww
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nipapwww'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 25, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'nipapwww'

What minimal ubuntu version to run nipap?i have tried install on ubuntu 22.04 got this error

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nipapd : Depends: nipap-common but it is not going to be installed
          Depends: python (>= 2.7) but it is not installable
          Depends: python-psycopg2 but it is not installable
          Depends: python-flask but it is not installable
          Depends: python-flask-xml-rpc but it is not going to be installed
          Depends: python-flask-restful but it is not installable
          Depends: python-flask-compress but it is not going to be installed
          Depends: python-tornado but it is not installable
          Depends: python-parsedatetime but it is not installable
          Depends: python-tz but it is not installable
          Depends: python-dateutil but it is not installable
          Depends: python-psutil but it is not installable
          Depends: python-pyparsing but it is not installable
          Depends: python-jwt but it is not installable
          Depends: python-requests but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jacobghattas** [comment]
same over here... 
>>> import nipapwww
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named nipapwww

**Comment by jacobghattas** [comment]
running ubuntu 20.04.6

**Comment by julianbeauregardcamp** [comment]
Getting the same type of error. Anyone got a fix for this on Ubuntu 20.04?

**Comment by atrogu** [comment]
Hello, my nipap installation on Ubuntu 20.04 gave the same errors, then I've found that it needed libapache2-mod-wsgi-py3 instead of libapache2-mod-wsgi installed.
