### ISSUE TITLE
nipap-passwd do not use unicode

### ISSUE THREAD

**Issue by SoundGoof** [SpriteLink/NIPAP#700]
nipap-passwd should use unicode instead of str

root@nipap:~# env
SHELL=/bin/bash
TERM=xterm
USER=root
TMOUT=1200
MAIL=/var/mail/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/root
LANG=en_US.UTF-8
SHLVL=1
HOME=/root
LOGNAME=root
HISTTIMEFORMAT=%F %T
_=/usr/bin/env
root@nipap:~# nipap-passwd -a testuser1 --password 'sdjdf866hjhjhvx' --name 'Arne Anka'
Added user testuser1 to database /etc/nipap/local_auth.db
root@nipap:~# nipap-passwd -a testuser2 --password 'sdjdf866hjhjhvx' --name 'Ärne Ånka'
Traceback (most recent call last):
  File "/usr/sbin/nipap-passwd", line 108, in <module>
    a.add_user(options.add_user, options.password, options.name, options.trusted, options.readonly)
  File "/usr/lib/python2.7/dist-packages/nipap/authlib.py", line 549, in add_user
    self._gen_hash(password, salt), full_name, trusted, readonly))
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str).            It is highly recommended that you instead just switch your application to Unicode strings.

**Comment by plajjan** [comment]
I had a quick look to see if we could convert this to Python3 but it's a little bit more complicated than I first imagined as nipap-passwd uses the nipapconfig class, which in turn relies on ConfigParser (renamed to configparser in py3).
