### ISSUE TITLE
Weird error message on duplicate

### ISSUE THREAD

**Issue by plajjan** [SpriteLink/NIPAP#765]
Trying to create a prefix that already exists usually results in the following:
```
>>> p2.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1076, in save
    raise _fault_to_exception(xml_fault)
pynipap.NipapDuplicateError: Duplicate value for 'prefix', the value '0, 1.3.3.0/24' is already in use.
```

In the above example I tried to create 1.3.3.0/24 as an assignment but that prefix already exists, as a reservation. If I now add  1.3.3.1/32 as an assignment and then try to create 1.3.3.0/24 again (as assignment) I will get:
```
>>> p2.save()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pynipap.py", line 1076, in save
    raise _fault_to_exception(xml_fault)
pynipap.NipapValueError: Prefix of type 'assignment' must not have any subnets other than of type 'host'
```

So it seems the check for what children a prefix contains comes first.. but it shouldn't. We should always give the duplicate message when there is a duplicate.

**Comment by plajjan** [comment]
It totally makes sense that the checks in the trigger runs before the unique check. Since we have the ability to modify the value in the before trigger PostgreSQL couldn't possibly check against the unique index before the trigger.

I don't quite like adding another SQL SELECT just to see whether a prefix already exists but I suppose I don't have much choice if I want to have a prettier message.
