### ISSUE TITLE
nipap-www is broken

### ISSUE THREAD

**Issue by plajjan** [SpriteLink/NIPAP#780]
The nipap-www debian package that is currently in the debian testing repo is broken. Apache spits out the following in its error log:
```
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26] mod_wsgi (pid=15868): Target WSGI script '/etc/nipap/nipap-www.wsgi' cannot be loaded as Python module.
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26] mod_wsgi (pid=15868): Exception occurred processing WSGI script '/etc/nipap/nipap-www.wsgi'.
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26] Traceback (most recent call last):
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/etc/nipap/nipap-www.wsgi", line 10, in <module>
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     application = loadapp('config:/etc/nipap/nipap-www.ini')
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     return loadobj(APP, uri, name=name, **kw)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     global_conf=global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     global_conf=global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 320, in _loadconfig
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     return loader.get_context(object_type, name, global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 454, in get_context
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     section)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 476, in _context_from_use
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     object_type, name=use, global_conf=global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 406, in get_context
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     global_conf=global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 296, in loadcontext
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     global_conf=global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 328, in _loadegg
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     return loader.get_context(object_type, name, global_conf)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 620, in get_context
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     object_type, name=name)
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]   File "/usr/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py", line 659, in find_egg_entry_point
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26]     for prot in protocol_options] or '(no entry points)'))))
[Mon May 18 16:50:39 2015] [error] [client 83.226.149.26] LookupError: Entry point 'main' not found in egg 'nipap-www' (dir: /usr/lib/python2.7/dist-packages; protocols: paste.app_factory, paste.composite_factory, paste.composit_factory; entry_points: )
```

**Comment by plajjan** [comment]
So, this error is from nipap-demo.spritelink.net and I found the cause, which was a stale nipap-www_0.27.2_egginfo directory that was almost empty.. dunno why it was there but upon removal it works with 0.28.

Not sure if it's reproducible on other boxes.. it feels like a one-off so I'm closing this.
